#server:
#  port: 3333
#
#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: greet-api
#          uri: http://localhost:9091
#          predicates:
#            - Path=/greet/**
#          filters:
#            - RewritePath=/greet/(?<segment>.*), /$\{segment}
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

server:
  port: 3333

spring:
  application:
    name: CLOUD-API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/greet

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix.eureka: DEBUG
